plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version "$kotlinVersion"
}

java {
    sourceCompatibility = rootProject.ext.javaCompatVersion
    targetCompatibility = rootProject.ext.javaCompatVersion
}

dependencies {
    implementation "com.google.devtools.ksp:symbol-processing-api:$kspVersion"
    implementation project(':funccallanno')
}