/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_NativeUtils */

#ifndef _Included_com_example_test_NativeUtils
#define _Included_com_example_test_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_NativeUtils
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_NativeUtils_getCString
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_test_NativeUtils_startNode
  (JNIEnv* env, jclass obj, jobjectArray args);

#ifdef __cplusplus
}
#endif
#endif
